version: '3.8'

services:
  zzuag-mysql:
    image: mysql:latest
    container_name: zzuag-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zzuag
      MYSQL_USER: zzuag
      MYSQL_PASSWORD: zzuag
      TZ: Asia/Seoul
    command: [ "--character-set-server=utf8mb4" ]
    ports:
      - "3306:3306"
    networks:
      - zzuag-network
  zzuag-adminer:
    image: adminer:latest
    container_name: zzuag-adminer
    environment:
      ADMINER_DEFAULT_SERVER: zzuag-mysql
    ports:
      - "18080:8080"
    networks:
      - zzuag-network
networks:
  zzuag-network:
    driver: bridge