spring:
  application:
    name: query-api
  config:
    activate:
      on-profile: prod
server:
  port: 8084
logging:
  level:
    org:
      springframework:
        security: DEBUG
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}