plugins {
    id 'java'
}

group = 'com.clubnu'
version = '0.0.1-SNAPSHOT'

bootJar {enabled = false}
jar {enabled = true}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':zzuag-common')
    // caffeine
    implementation 'com.github.ben-manes.caffeine:caffeine'
    // spring-boot-starter-cache
    implementation 'org.springframework.boot:spring-boot-starter-cache'

}

test {
    useJUnitPlatform()
}