version: '3.8'

services:
  zzuag-mysql:
    image: mysql:latest
    container_name: zzuag-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zzuag
      MYSQL_USER: zzuag
      MYSQL_PASSWORD: zzuag
      TZ: Asia/Seoul
    command: [ "--character-set-server=utf8mb4" ]
    ports:
      - "3306:3306"
    networks:
      - zzuag-network
  zzuag-adminer:
    image: adminer:latest
    container_name: zzuag-adminer
    environment:
      ADMINER_DEFAULT_SERVER: zzuag-mysql
    ports:
      - "18080:8080"
    networks:
      - zzuag-network
  zzuag-redis:
    image: redis:latest
    container_name: zzuag-redis
    ports:
      - "6379:6379"
    networks:
      - zzuag-network
#  zookeeper-1:
#    image: confluentinc/cp-zookeeper:latest
#    ports:
#      - '32181:32181'
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 32181
#      ZOOKEEPER_TICK_TIME: 2000
#  kafka-1:
#    image: confluentinc/cp-kafka:latest
#    ports:
#      - '9092:9092'
#    depends_on:
#      - zookeeper-1
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
#      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_NUM_PARTITIONS: 1
#  kafka-ui:
#    image: provectuslabs/kafka-ui
#    container_name: kafka-ui
#    ports:
#      - "8989:8080"
#    restart: always
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:29092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-1:22181
networks:
  zzuag-network:
    driver: bridge