version: '3.8'

services:
  zzuag-app:
    image: sso9594/zzuag
    container_name: zzuag-app
    build:
      context: .
      dockerfile: Dockerfile  # assuming your Dockerfile is in the current directory
    platform: linux/amd64
    ports:
      - "8082:8082"
    environment:
      DB_HOST: zzuag-mysql
      DB_PORT: 3306
      DB_SOURCE: zzuag
      DB_USER: zzuag
      DB_PASSWORD: zzuag
      REDIS_HOST: zzuag-redis
      REDIS_PORT: 6379
      PINPOINT_AGENT_ID: syoung
      PINPOINT_APPLICATION_NAME: zzuag-Test
      PINPOINT_CONFIG: /pinpoint-agent/pinpoint-root.config  # Pinpoint config path inside the container
    depends_on:
      - zzuag-mysql
      - zzuag-redis
    networks:
      - zzuag-network
    volumes:
      - ./pinpoint-agent-3.0.0/:/pinpoint-agent

  zzuag-mysql:
    image: mysql:latest
    container_name: zzuag-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zzuag
      MYSQL_USER: zzuag
      MYSQL_PASSWORD: zzuag
      TZ: Asia/Seoul
    command: [
      "--character-set-server=utf8mb4",
      "--secure-file-priv=/docker-entrypoint-initdb.d/dummy"
    ]
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - zzuag-network

  zzuag-adminer:
    image: adminer:latest
    container_name: zzuag-adminer
    environment:
      ADMINER_DEFAULT_SERVER: zzuag-mysql
    ports:
      - "18080:8080"
    networks:
      - zzuag-network

  zzuag-redis:
    image: redis:latest
    container_name: zzuag-redis
    ports:
      - "6379:6379"
    networks:
      - zzuag-network

  controller:
    image: ngrinder/controller
    platform: linux/amd64
    restart: always
    ports:
      - "9000:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller
  agent:
    image: ngrinder/agent
    platform: linux/amd64
    restart: always
    links:
      - controller

networks:
  zzuag-network:
    driver: bridge
