plugins {
    id 'java'
}

group = 'com.recycle'
version = '0.0.1-SNAPSHOT'

bootJar {enabled = false}
jar {enabled = true}

repositories {
    mavenCentral()
}

dependencies {
    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // jackson
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
}

test {
    useJUnitPlatform()
}